application: selpeeps
version: 1
runtime: python27
api_version: 1
threadsafe: yes

inbound_services:
- mail

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest


handlers:
- url: /static
  static_dir: static

- url: /_ah/mail/.+
  script: main.app
  login: admin

- url: .*
  script: main.app
